name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  js-lint:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./dex/tests/permissioned
    name: Prettier check
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: corepack enable
      shell: bash
    - run: yarn
    - name: Run prettier
      run: yarn prettier '*/**/*{.js,.ts}' --check
  rust-lint:
    name: Cargo fmt, cargo clippy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Cache Cargo and target
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            dex/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run cargo fmt
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            dex/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: test
        run: |
          cargo test --manifest-path Cargo.toml --all
          cargo test --manifest-path dex/Cargo.toml --all
